[package]
name = "guessing_game_web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3.77"
web-sys = { version = "0.3.77", features = ["Window", "HtmlInputElement", "Document"] }




