[package]
name = "guessing_game_web"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8"

[lib]
crate-type = ["cdylib", "rlib"]


